# Generated by Django 5.2.5 on 2025-08-13 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('no_of_guests', models.IntegerField(db_column='No_of_guests', validators=[django.core.validators.MinValueValidator(1)])),
                ('booking_date', models.DateTimeField(db_column='BookingDate')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('inventory', models.IntegerField(db_column='Inventory', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'Menu',
            },
        ),
    ]
